# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('week_care_commences', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='core.Client')),
            ],
        ),
        migrations.CreateModel(
            name='PregnancyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_events', to='core.Pregnancy')),
            ],
        ),
    ]
